name: CI

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-24.04
    outputs:
      jobs: ${{ steps.compute-matrix.outputs.jobs }}
    env:
      DOTNET_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/workflows

      - uses: nike4613/install-dotnet@6625f6cf2b076b088eee77a005f5f226e89aa580
        with:
          global-json: ./.github/workflows/gen-matrix/global.json
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Compute matrix
        id: compute-matrix
        run: dotnet run --project ./.github/workflows/gen-matrix/gen-matrix.csproj -c Release

  build:
    needs: [ setup ]
    strategy:
      matrix: ${{ needs.setup.result == 'success' && fromJSON(needs.setup.outputs.jobs) || '' }}
      fail-fast: false
    name: ${{ matrix.name }}
    uses: ./.github/workflows/build.yml
    with:
      strategy: ${{ toJSON(matrix.strategy) }}
    secrets: inherit
